### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by adamq-q** [Ezelia/EPSy#3]
This plugin is awesome. Has anyone had any luck getting this working in a TypeScript Phaser project?

**Comment by alaa-eddine** [comment]
Hi, the plugin is writted in TypeScript and is 100% compatible with Phaser TS projects :)
did you encountered any issue while importing code to a Phaser project ?

**Comment by adamq-q** [comment]
Hi, I noticed that right after I posted the question! And thank you for bearing with me as I'm new to TypeScript. I see that all the build files are all JS. So would I just want to include the 3 .ts files found in /core?

**Comment by alaa-eddine** [comment]
I just updated the build with TS definitions for EPSY so you can use it to get intellisense completion (I guess this is why you wanted TS integration).
the EPSY.d.ts file will give you the completion feature.

for Phaser and Pixi plugins they are written with vanilla JS so I can't generate .d.ts files for them, I'll create .d.ts manually later :)  but you don't really need them since the code you need to know is what's generated from EPSY Editor
